"""Add server management  tables

Revision ID: a4195b1b8993
Revises: 
Create Date: 2026-09-07 14:27:00.968950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4195b1b8993'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('repo_url', sa.String(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('repo_url')
    )
    op.create_table('manifest_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('allowed_destinations', sa.JSON(), nullable=False),
    sa.Column('tool_declarations', sa.JSON(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_runs',
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PULLING_CODE', 'RULE_ANALYSIS_RUNNING', 'RULE_ANALYSIS_PASSED', 'LLM_ANALYSIS_RUNNING', 'REJECTED', 'STATIC_ANALYSIS_PASSED', 'BUILDING_CONTAINER', 'SANDBOX_RUNNING', 'SCORING', 'COMPLETE', 'FAILED', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('scan_run_id')
    )
    op.create_table('server_manifests',
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('allowed_destinations', sa.JSON(), nullable=False),
    sa.Column('tool_declarations', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.server_id'], ),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_table('llm_analysis_results',
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'PASS_WITH_FINDINGS', 'FAIL', name='llmverdict'), nullable=False),
    sa.Column('llm_findings', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.scan_run_id'], ),
    sa.PrimaryKeyConstraint('scan_run_id')
    )
    op.create_table('rule_analysis_results',
    sa.Column('scan_run_id', sa.String(), nullable=False),
    sa.Column('verdict', sa.Enum('PASS', 'PASS_WITH_FINDINGS', 'FAIL', name='ruleverdict'), nullable=False),
    sa.Column('rule_findings', sa.JSON(), nullable=False),
    sa.Column('tool_declarations', sa.JSON(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.scan_run_id'], ),
    sa.PrimaryKeyConstraint('scan_run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_analysis_results')
    op.drop_table('llm_analysis_results')
    op.drop_table('server_manifests')
    op.drop_table('scan_runs')
    op.drop_table('manifest_history')
    op.drop_table('servers')
    # ### end Alembic commands ###
