package analyze

import (
	"fmt"
	"sort"
)

// UnexpectedExec reports any process execution beyond the entrypoint.
//
// An MCP stdio server is one long-lived process reading JSON-RPC off its
// stdin. Almost nothing it legitimately does requires spawning another
// program, so the base rate of this behaviour is close to zero — which is
// what makes it a good detector. Every `execve` after the first is worth
// a human looking at it.
type UnexpectedExec struct{}

func (UnexpectedExec) Name() string   { return "unexpected-exec" }
func (UnexpectedExec) Family() Family { return FamilySupplyChain }

func (d UnexpectedExec) Inspect(s *Snapshot) []Finding {
	entry := s.Entrypoint.Path
	seen := map[string]bool{}
	var extra []string
	for _, w := range s.AllWindows() {
		if w == nil {
			continue
		}
		for _, e := range w.Execs {
			if e == entry || e == s.Entrypoint.Interpreter || seen[e] {
				continue
			}
			seen[e] = true
			extra = append(extra, e)
		}
	}
	if len(extra) == 0 {
		return nil
	}
	sort.Strings(extra)
	return []Finding{mk(d, "exec", SeverityHigh, ConfidenceDeterministic,
		"process spawned beyond the entrypoint",
		fmt.Sprintf("%d distinct executable(s) were run that are not the declared entrypoint", len(extra)),
		extra...)}
}

// NativeCodeLoad reports shared objects loaded from outside the declared
// read set.
//
// Native code is the blind spot of every dependency audit: a package
// manifest review, an SBOM, and a source-level scan all inspect source,
// and a `.node` or `.so` loaded at runtime is none of those things. If
// the profile did not declare the path it came from, no human approved
// the code now executing in the process.
type NativeCodeLoad struct{}

func (NativeCodeLoad) Name() string   { return "native-code-load" }
func (NativeCodeLoad) Family() Family { return FamilySupplyChain }

func (d NativeCodeLoad) Inspect(s *Snapshot) []Finding {
	if !s.Baseline.HasProfile() {
		return nil
	}
	var undeclared, writable []string
	for p, a := range s.Totals.Paths {
		if !IsSharedObject(p) || a.Kind == AccessStat {
			continue
		}
		if s.Baseline.AllowsWrite(p) {
			writable = append(writable, p)
			continue
		}
		if !s.Baseline.AllowsRead(p) {
			undeclared = append(undeclared, p)
		}
	}
	sort.Strings(undeclared)
	sort.Strings(writable)

	var out []Finding
	if len(writable) > 0 {
		out = append(out, mk(d, "writable", SeverityCritical, ConfidenceDeterministic,
			"native library loaded from a writable path",
			"a shared object was opened from a path the server itself can write; that library's contents are not what any review saw",
			writable...))
	}
	if len(undeclared) > 0 {
		out = append(out, mk(d, "undeclared", SeverityHigh, ConfidenceDeterministic,
			"native library loaded from an undeclared path",
			fmt.Sprintf("%d shared object(s) were loaded from outside the declared read set", len(undeclared)),
			undeclared...))
	}
	return out
}

// ModuleDrift reports dependency files loaded that the approved profile
// does not cover.
//
// This is the practical shape of a supply-chain compromise against an MCP
// server. The attack is not usually a new syscall or a new network
// destination; it is version 4.0.2 of a transitive dependency shipping a
// file that version 4.0.1 did not have. The profile was generated by
// observing the server at review time, so the set of module files it
// declares *is* the reviewed dependency set, and a module path outside it
// is a dependency tree that changed after approval.
type ModuleDrift struct{}

func (ModuleDrift) Name() string   { return "module-drift" }
func (ModuleDrift) Family() Family { return FamilySupplyChain }

func (d ModuleDrift) Inspect(s *Snapshot) []Finding {
	if !s.Baseline.HasProfile() {
		return nil
	}
	var drifted []string
	for p, a := range s.Totals.Paths {
		if !IsModulePath(p) || a.Kind == AccessStat {
			continue
		}
		// A package directory the profile granted files inside of is part
		// of the reviewed dependency set, not a change to it.
		if s.Baseline.IsAncestorOfGrant(p) {
			continue
		}
		// A module file that was looked for and not found is resolution
		// noise, not drift: every module loader probes paths that do not
		// exist.
		if a.Opens > 0 && a.Errors >= a.Opens {
			continue
		}
		if !s.Baseline.AllowsRead(p) {
			drifted = append(drifted, p)
		}
	}
	if len(drifted) == 0 {
		return nil
	}
	sort.Strings(drifted)
	return []Finding{mk(d, "drift", SeverityHigh, ConfidenceDeterministic,
		"dependency loaded that was absent at approval",
		fmt.Sprintf("%d file(s) inside a package directory were loaded that the approved profile does not cover — the dependency tree has changed since review", len(drifted)),
		drifted...)}
}

// EntrypointDrift compares the executable actually started against the
// digest the profile pins.
//
// This is the one detector that can fire before a single request is
// served, and the only one that covers the ELF interpreter — code that
// runs in every dynamically linked process and appears in no syscall
// trace, because the sandbox's own kernel maps it inside execve.
type EntrypointDrift struct{}

func (EntrypointDrift) Name() string   { return "entrypoint-drift" }
func (EntrypointDrift) Family() Family { return FamilySupplyChain }

func (d EntrypointDrift) Inspect(s *Snapshot) []Finding {
	pinned := s.Baseline.Entrypoint
	got := s.Entrypoint
	if pinned == nil {
		if got.SHA256 == "" {
			return nil
		}
		// Informational, not a deviation: nothing was observed to be
		// wrong. It says the profile could be stronger, which must not
		// be able to move a server's tier on its own.
		return []Finding{mk(d, "unpinned", SeverityInfo, ConfidenceDeterministic,
			"entrypoint is not pinned by the profile",
			"the running executable was measured but the profile declares no expected digest, so a substituted binary would not be detected",
			"measured "+got.Path+" = "+got.SHA256,
			"interpreter "+got.Interpreter+" = "+got.InterpreterSHA256)}
	}
	var out []Finding
	if got.Err != "" {
		out = append(out, mk(d, "unmeasurable", SeverityHigh, ConfidenceDeterministic,
			"entrypoint could not be measured",
			"the profile pins an entrypoint digest but the running executable could not be hashed: "+got.Err))
		return out
	}
	if pinned.SHA256 != "" && pinned.SHA256 != got.SHA256 {
		out = append(out, mk(d, "binary", SeverityCritical, ConfidenceDeterministic,
			"entrypoint does not match the attested digest",
			"the executable running in this container is not the one the profile was approved for",
			"expected "+pinned.SHA256, "measured "+got.SHA256))
	}
	if pinned.InterpreterSHA256 != "" && pinned.InterpreterSHA256 != got.InterpreterSHA256 {
		out = append(out, mk(d, "interpreter", SeverityCritical, ConfidenceDeterministic,
			"ELF interpreter does not match the attested digest",
			"the dynamic loader mapping this process is not the one that was reviewed; it executes before any application code and appears in no syscall trace",
			"expected "+pinned.InterpreterSHA256, "measured "+got.InterpreterSHA256))
	}
	return out
}

// ProcessSpawn reports fork/clone volume above what a stdio server needs.
//
// Runtimes legitimately create threads — Node starts a libuv pool, Python
// may start a few — so this measures against a generous fixed budget and
// against the session's own history, not against zero.
type ProcessSpawn struct {
	// Budget is the fork/clone count tolerated during startup.
	Budget int
}

func (ProcessSpawn) Name() string   { return "process-spawn" }
func (ProcessSpawn) Family() Family { return FamilySupplyChain }

func (d ProcessSpawn) Inspect(s *Snapshot) []Finding {
	budget := d.Budget
	if budget <= 0 {
		budget = 64
	}
	var out []Finding
	// Spawning during startup is normal; spawning while serving is not.
	for _, w := range s.CompletedRequests() {
		if w.Forks == 0 {
			continue
		}
		sev := SeverityLow
		if w.Forks > 8 {
			sev = SeverityMedium
		}
		out = append(out, mk(d, "per-request", sev, ConfidenceHeuristic,
			"new processes or threads created while serving a request",
			fmt.Sprintf("request %s created %d process/thread(s); a stdio MCP server normally creates none after startup", w.RequestID, w.Forks)))
		break // one finding for the condition, counted by the engine
	}
	if s.Totals.Forks > budget {
		out = append(out, mk(d, "total", SeverityMedium, ConfidenceHeuristic,
			"sustained process creation",
			fmt.Sprintf("%d fork/clone calls over the session, past a budget of %d", s.Totals.Forks, budget)))
	}
	return out
}
