// Command warden-launch is the one-command path from "a GitHub repo" to
// "a confined, monitored MCP server with a live dashboard": it clones the
// repository, detects and builds a runnable entrypoint, profiles it in
// learning mode, auto-approves the resulting CapabilityProfile, and hands
// off to warden-serve for enforced execution with -live until you stop
// it.
//
//	warden-launch -repo https://github.com/org/some-mcp-server
//	warden-launch https://github.com/org/some-mcp-server        # -repo is positional too
//
// Two things this command does are worth knowing before you point it at
// something:
//
//  1. Cloning and dependency installation (npm install, pip install, go
//     build) run UNCONFINED on this host — see sandbox/fetch's package
//     doc. Only the server process itself, once detected, ever runs
//     inside gVisor.
//  2. The capability profile is generated by learning mode (itself an
//     unconfined execution, §6.4) and then auto-approved by this tool
//     rather than by a human — the fast path the architecture's §3.2
//     step 5 calls out as the thing never to do silently. warden-launch
//     does it loudly instead: the approver name says exactly what
//     happened, and it is printed in red before enforcement starts. Use
//     warden-observe -emit-profile and review it yourself if you want
//     the reviewed path instead of the fast one.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"mcp-warden/sandbox/fetch"
	"mcp-warden/sandbox/observe"
)

const (
	ansiReset    = "\033[0m"
	ansiBold     = "\033[1m"
	ansiDim      = "\033[2m"
	ansiRed      = "\033[31m"
	ansiYellow   = "\033[33m"
	ansiCyan     = "\033[36m"
	autoApprover = "operator:auto (warden-launch fast-path — NOT human-reviewed, see docs/ARCHITECTURE.md §3.2 step 5)"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "warden-launch:", err)
		os.Exit(1)
	}
}

type stringList []string

func (s *stringList) String() string     { return strings.Join(*s, ",") }
func (s *stringList) Set(v string) error { *s = append(*s, v); return nil }

func run(args []string) error {
	fs := flag.NewFlagSet("warden-launch", flag.ContinueOnError)
	repo := fs.String("repo", "", "git URL of the MCP server to run (also accepted as the first positional argument)")
	ref := fs.String("ref", "", "branch or tag to clone (default: the repository's default branch)")
	entrypoint := fs.String("entrypoint", "", "override detection: the exact command to run, e.g. \"node build/index.js\"")
	requestsFile := fs.String("requests", "", "newline-delimited JSON-RPC requests to send during learning mode (default: initialize + tools/list)")
	network := fs.String("network", "none", "network mode during learning-mode profiling: none, sandbox, or host")
	var writePaths stringList
	fs.Var(&writePaths, "write-path", "path prefix the server may write to, granted in the generated profile (repeatable)")
	toolName := fs.String("name", "", "tool name in the generated profile (default: derived from the repo URL)")
	learnTimeout := fs.Duration("learn-timeout", 60*time.Second, "overall timeout for the learning-mode profiling run")
	reqTimeout := fs.Duration("request-timeout", 15*time.Second, "per-request timeout, both during profiling and once enforced")
	pool := fs.Int("pool", 2, "warm confined containers to keep once enforced")
	addr := fs.String("addr", "127.0.0.1:8080", "listen address for the enforced daemon's HTTP endpoints")
	analyzeMode := fs.String("analyze", "detect", "behavioural analysis: off | detect | full")
	auditPath := fs.String("audit", "", "audit log path (default: <clone dir>/audit.jsonl)")
	noAudit := fs.Bool("no-audit", false, "disable the audit log entirely")
	live := fs.Bool("live", true, "render the live terminal dashboard (this is the point of this command; -live=false just runs the HTTP daemon)")
	memLimit := fs.Int64("memory-bytes", 0, "container memory cap (0 = default)")
	pidLimit := fs.Int64("pid-limit", 0, "container process/thread cap (0 = default)")
	keepSrc := fs.Bool("keep-src", false, "don't delete the cloned source tree on exit")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *repo == "" && fs.NArg() > 0 {
		*repo = fs.Arg(0)
	}
	if *repo == "" {
		return fmt.Errorf("a repository URL is required: warden-launch -repo <git-url> (or warden-launch <git-url>)")
	}

	repoRoot, err := findModuleRoot()
	if err != nil {
		return err
	}
	if os.Geteuid() != 0 {
		warn("not running as root — gVisor (runsc) needs real root for both the learning-mode pass below and the enforced run that follows, unless this host has rootless runsc fully configured (newuidmap/newgidmap + cgroup v2 delegation). If the next steps fail with a permissions error, rerun under sudo. Note that running the whole command under sudo also means the UNCONFINED dependency install below (npm/pip/go build) runs as root, not just unconfined — a real tradeoff, not just a formality.")
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	banner("cloning %s%s", *repo, refSuffix(*ref))
	cloneDir, err := fetch.Clone(ctx, *repo, *ref)
	if err != nil {
		return err
	}
	if !*keepSrc {
		defer os.RemoveAll(cloneDir)
	} else {
		fmt.Printf("source tree kept at %s\n", cloneDir)
	}

	warn("dependency installation and any build step below runs UNCONFINED on this host (see sandbox/fetch package doc) — only the detected server process is sandboxed")

	detectOpts := fetch.Options{}
	if *entrypoint != "" {
		detectOpts.Manual = strings.Fields(*entrypoint)
		detectOpts.Cwd = cloneDir
	}
	ep, err := fetch.Detect(ctx, cloneDir, detectOpts)
	if err != nil {
		return err
	}
	banner("detected a %s entrypoint", ep.Kind)
	for _, n := range ep.Notes {
		fmt.Printf("  %s· %s%s\n", ansiDim, n, ansiReset)
	}
	fmt.Printf("  command: %s\n", strings.Join(ep.Command, " "))

	binDir := filepath.Join(os.TempDir(), "mcp-warden-launch-bin")
	if err := os.MkdirAll(binDir, 0o755); err != nil {
		return fmt.Errorf("create build cache dir: %w", err)
	}
	probeBin := filepath.Join(binDir, "probe")
	serveBin := filepath.Join(binDir, "warden-serve")
	banner("building helper binaries (cached under %s)", binDir)
	if err := goBuild(ctx, repoRoot, probeBin, "./sandbox/runtime/runsc/probe"); err != nil {
		return fmt.Errorf("build probe: %w", err)
	}
	if err := goBuild(ctx, repoRoot, serveBin, "./cmd/warden-serve"); err != nil {
		return fmt.Errorf("build warden-serve: %w", err)
	}

	requests, err := loadLearningRequests(*requestsFile)
	if err != nil {
		return err
	}

	warn("LEARNING MODE — the server runs completely UNCONFINED for this profiling pass (§6.4). It is about to execute with no seccomp filter, no path confinement, network=%s.", *network)
	learnCtx, cancel := context.WithTimeout(ctx, *learnTimeout)
	report, obsErr := observe.Run(learnCtx, observe.Target{
		Command:     ep.Command,
		Cwd:         ep.Cwd,
		Requests:    requests,
		NetworkMode: *network,
	}, observe.RunOptions{Timeout: *learnTimeout, RequestTimeout: *reqTimeout})
	cancel()
	if obsErr != nil && report == nil {
		return fmt.Errorf("learning-mode run: %w", obsErr)
	}
	if len(report.Syscalls) == 0 {
		detail := report.ExitErr
		if detail == "" {
			detail = "no exit error was recorded either; rerun with warden-observe " + strings.Join(ep.Command, " ") + " for a detailed trace"
		}
		return fmt.Errorf("learning-mode run observed no syscalls at all — the server likely failed to start: %s", detail)
	}

	name := *toolName
	if name == "" {
		name = repoToolName(*repo)
	}
	cand, err := observe.GenerateProfile(report, observe.ProfileOptions{
		ToolName:   name,
		WritePaths: writePaths,
	})
	if err != nil {
		return fmt.Errorf("generate profile: %w", err)
	}
	cand.Profile.ApprovedBy = autoApprover

	if len(cand.BroadGrants) > 0 {
		warn("this profile grants whole system trees: %s — auto-approving anyway per the fast-path you chose, but this is a materially weaker profile than a narrow one", strings.Join(cand.BroadGrants, ", "))
	}

	profilePath := filepath.Join(cloneDir, ".warden-profile.json")
	data, err := json.MarshalIndent(cand.Profile, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal profile: %w", err)
	}
	if err := os.WriteFile(profilePath, append(data, '\n'), 0o644); err != nil {
		return fmt.Errorf("write profile: %w", err)
	}

	tool := cand.Profile.Tools[0]
	banner("candidate profile auto-approved")
	fmt.Printf("  approved_by:      %s%s%s\n", ansiRed, cand.Profile.ApprovedBy, ansiReset)
	fmt.Printf("  syscalls granted: %d\n", len(tool.Syscalls))
	fmt.Printf("  read paths:       %d\n", len(tool.Filesystem.Read))
	fmt.Printf("  write paths:      %d\n", len(tool.Filesystem.Write))
	fmt.Printf("  network declared: %d destination(s)\n", len(tool.Network))
	fmt.Printf("  written to:       %s\n", profilePath)

	audit := *auditPath
	if !*noAudit && audit == "" {
		audit = filepath.Join(cloneDir, "audit.jsonl")
	}
	if *noAudit {
		audit = ""
	}

	serveArgs := []string{
		"-profile", profilePath,
		"-probe", probeBin,
		"-addr", *addr,
		"-pool", strconv.Itoa(*pool),
		"-analyze", *analyzeMode,
		"-request-timeout", reqTimeout.String(),
		"-cwd", ep.Cwd,
	}
	if audit != "" {
		serveArgs = append(serveArgs, "-audit", audit)
	}
	if *live {
		serveArgs = append(serveArgs, "-live")
	}
	if *memLimit > 0 {
		serveArgs = append(serveArgs, "-memory-bytes", strconv.FormatInt(*memLimit, 10))
	}
	if *pidLimit > 0 {
		serveArgs = append(serveArgs, "-pid-limit", strconv.FormatInt(*pidLimit, 10))
	}
	serveArgs = append(serveArgs, "--")
	serveArgs = append(serveArgs, ep.Command...)

	banner("handing off to warden-serve — enforced, monitored, live until you press Ctrl-C")
	cmd := exec.Command(serveBin, serveArgs...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start warden-serve: %w", err)
	}

	// warden-serve installs its own SIGINT/SIGTERM handler and shuts down
	// gracefully (drains requests, destroys containers, closes the audit
	// chain, prints a final report). Forward the signal explicitly rather
	// than relying on shared process-group delivery: an interactive Ctrl-C
	// happens to reach both processes because they share a terminal, but
	// this must also work when the parent alone is signalled — a process
	// supervisor sending SIGTERM to warden-launch's own PID, for instance
	// — or the child never learns to shut down and its containers and
	// audit chain are simply abandoned.
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt, syscall.SIGTERM)
	go func() {
		for s := range sig {
			_ = cmd.Process.Signal(s)
		}
	}()
	defer signal.Stop(sig)

	waitErr := cmd.Wait()

	var exitErr *exec.ExitError
	if errors.As(waitErr, &exitErr) {
		os.Exit(exitErr.ExitCode())
	}
	return waitErr
}

func banner(format string, args ...any) {
	fmt.Printf("\n%s%s▶ %s%s\n", ansiBold, ansiCyan, fmt.Sprintf(format, args...), ansiReset)
}

func warn(format string, args ...any) {
	fmt.Printf("%s%s⚠ %s%s\n", ansiBold, ansiYellow, fmt.Sprintf(format, args...), ansiReset)
}

func refSuffix(ref string) string {
	if ref == "" {
		return ""
	}
	return " @ " + ref
}

// findModuleRoot verifies the command is being run from the mcp-warden
// repository root, which it needs in order to `go build` warden-serve
// and the probe binary. It walks up from the working directory the way
// `go build` itself resolves a module, rather than assuming cwd is
// already the root.
func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if data, err := os.ReadFile(filepath.Join(dir, "go.mod")); err == nil {
			if strings.HasPrefix(string(data), "module mcp-warden") {
				return dir, nil
			}
			return "", fmt.Errorf("found go.mod at %s but it is not mcp-warden's — run warden-launch from inside the mcp-warden repository", dir)
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.mod found above %s — run warden-launch from inside the mcp-warden repository (it builds warden-serve and the probe binary from source)", dir)
		}
		dir = parent
	}
}

func goBuild(ctx context.Context, repoRoot, out, pkg string) error {
	cmd := exec.CommandContext(ctx, "go", "build", "-o", out, pkg)
	cmd.Dir = repoRoot
	cmd.Stdout = os.Stderr
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func repoToolName(repo string) string {
	trimmed := strings.TrimSuffix(strings.TrimSuffix(repo, "/"), ".git")
	if u, err := url.Parse(trimmed); err == nil && u.Path != "" {
		trimmed = u.Path
	}
	parts := strings.Split(trimmed, "/")
	name := parts[len(parts)-1]
	if name == "" {
		return "launched"
	}
	return name
}

func loadLearningRequests(path string) ([][]byte, error) {
	if path == "" {
		return [][]byte{
			observe.DefaultMCPInitializeRequest(),
			[]byte(`{"jsonrpc":"2.0","id":2,"method":"tools/list"}`),
		}, nil
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read -requests file: %w", err)
	}
	var out [][]byte
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		out = append(out, []byte(line))
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("-requests file %s contained no requests", path)
	}
	return out, nil
}
